# Generated by Django 3.1 on 2020-08-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choicetest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceTest',
        ),
    ]
